server:
  port: 8101

spring:
  cloud:
    gateway:
      server:
        webflux: {}  # keep it empty if no specific settings
      discovery:
        locator:
          enabled: true
      routes:
        - id: keycloak-service
          uri: lb://KEYCLOAK-SERVICE
          predicates:
            - Path=/{realm}/keycloak/**
        - id: Service-Catalog
          uri: lb://SERVICE-CATALOG
          predicates:
            - Path=/{realm}/Saloons/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true